### ISSUE TITLE
Exit when the child process exits

### ISSUE THREAD

**Issue by eknkc** [chazomaticus/minit#1]
Hi!

As far as I can tell, minit will run indefinitely, until it receives a `SIGTERM`. 

Is there any way to track the first child process (`/etc/minit/startup`) and wait until it exits, then have it exit itself? 

I'd like to have it as PID1 on long running foreground processes, reaping zombies and follow the child process to grave. This would not be suitable for forking daemons but a command flag to enable it might be useful in certain situations.

**Comment by chazomaticus** [comment]
I'm confused--why even use minit in this scenario?  Why not just exec whatever daemon you're trying to run directly as the Docker root process (assuming you're inside Docker)?  I believe the default behavior is for processes to reap their children, so unless the daemon goes out of its way to avoid doing so, I don't think minit would really be adding anything here (except maybe exec'ing a script when it shuts down?).

**Comment by chazomaticus** [comment]
@eknkc, I've given your proposal a bit more thought, and I can see scenarios where the behavior you describe would be handy.  I've got a branch [ex-it](https://github.com/chazomaticus/minit/tree/ex-it) with some preliminary work on it.  I haven't decided what exactly to do with it yet.

**Comment by yrn1** [comment]
It would be very handy to have ex-it pass all extra command line arguments too. Sort-of make it like the 'time' command (but instead of measuring time, it reaps zombies).
I'm wondering now if this could even work for daemonizing programs: since ex-it is pid 1, every process would be its child, also daemonized ones, so it could also wait for them to exit by themselves.

**Comment by chazomaticus** [comment]
@yrn1: I've updated the readme so it's clearer how to run it.  (It behaves like you describe, passing args on to the exec'd process.)

Also, I realized when I replied to @eknkc that I was conflating daemons with foreground processes.  Minit is more useful to containers running daemons and multiple processes, where the container should stay up until the root/init process is killed.  Ex-it might be more useful when only one foreground process is running, where that program's exit should bring down the container.

Other ideas to consider would be minit automatically calling shutdown and exiting when it had no more child processes in its process space (which could make it more useful to run multiple background, shorter-lived tasks), or ex-it staying alive as long as it had any child processes in its process space, eventually returning the status of its exec'd child (which could make it more useful for running multiple foreground programs).  Then the big difference would be whether they exec'd startup/shutdown routines.  I don't know--I'm open to thoughts on how useful either case might be.

**Comment by chazomaticus** [comment]
@eknkc, I believe your problem has been addressed in #2.  I don't think I fully understood all the different use cases here--looking back it seems [dumb-init](https://github.com/Yelp/dumb-init) might've been more suited to your needs, if it existed at that point.  Either way, now it'll always exit when there are no more child processes, including the startup process.

@yrn1, again I believe dumb-init behaves more like you describe with regards to argument passing.

Thanks to both of you!
