### ISSUE TITLE
Minit should exit with the exit status of minit/startup if this script fails

### ISSUE THREAD

**Issue by ricardobranco777** [chazomaticus/minit#2]
If the minit/startup script fails, minit should exit with the exit status of the script to detect errors on deployment.  Currently, it always returns 0 whether the script ran ok or not.

**Comment by chazomaticus** [comment]
This sounds like a good idea to me!  The key to staying agnostic about how the startup script behaves (i.e. is it a symlink to the actual service, or a script that starts potentially several services then exits while they run) is to exit early from minit only if the startup script returns failure.  That's exactly what you said, but I wanted to call out how important that detail is.

While we're at it, it might be worth reexamining the `exit(1);` call issued when the exec fails.  If there's another value besides 1 we could return that, by some convention, means it couldn't exec the given script, that might help diagnose such failures, with this new feature.

I probably won't have time to work on this any time soon, but if anyone wants to submit a PR I might have time to review it.

Thanks @ricardobranco777!

**Comment by ricardobranco777** [comment]
@chazomaticus I'm working on it and submit a PR as soon as possible.

I suggest this convention for exit status:

Exit with the same exit status of the startup script, or 128 + signal number if the script was terminated by a signal.  This follows some shells convention.

The `exit(1);` should be changed to `exit(-1);`  In the shell `$?` would be 255.

**Comment by chazomaticus** [comment]
Fixed with #3 landing.
